spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.248.129:8808
      config:
        server-addr: http://192.168.248.129:8808
    #        endpoint: '*'
    gateway:
      routes:
        - id: route-product
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/(?<segment>.*), /$\{segment}

        - id: route-webapp
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}


