server:
  port: 5301

spring:
  application:
    name: mall-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
    url: jdbc:mysql://192.168.248.129:3306/mall-oms?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml
